import Head from "next/head";
import { routes } from "@/config/router";
import { useEffect, useState } from "react";

export default function CommonHead() {
  const [title, setTitle] = useState("ElevenDing");
  useEffect(() => {
    const pathname = window.location.pathname;
    const text = routes.find((route) => route.link === pathname)?.text ?? "";

    setTitle(text);

    function listenVisibilitychange() {
      if (document.visibilityState === "visible") {
        setTitle(text);
      } else if (document.visibilityState === "hidden") {
        setTitle("别走，再看我一眼 -");
      }
    }
    document.addEventListener("visibilitychange", listenVisibilitychange);
    return () => {
      document.removeEventListener("visibilitychange", listenVisibilitychange);
    };
  }, []);

  return (
    <Head>
      <title>{title + " ElevenDing"}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
